export const ON_SAVE_LIST_MOVIE = "ON_SAVE_LIST_MOVIE";
export const ON_SAVE_LIST_CINEMA = "ON_SAVE_LIST_CINEMA";
export const DETAIL_MOVIE = "DETAIL_MOVIE";
export const DETAIL_CINEMA = "DETAIL_CINEMA";
export const DETAIL_SHOWTIME = "DETAIL_SHOWTIME";
export const ON_SAVE_LIST_SHOWTIME = "ON_SAVE_LIST_SHOWTIME";

//login
export const LOGIN = "LOGIN";

